export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  LOAN_OFFICER = 'LOAN_OFFICER',
  PROCESSOR = 'PROCESSOR',
  READ_ONLY = 'READ_ONLY',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  DISABLED = 'DISABLED',
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  QUALIFIED = 'QUALIFIED',
  DISQUALIFIED = 'DISQUALIFIED',
  CONVERTED = 'CONVERTED',
}

export enum LoanStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PROCESSING = 'PROCESSING',
  CONDITIONAL_APPROVAL = 'CONDITIONAL_APPROVAL',
  CLEAR_TO_CLOSE = 'CLEAR_TO_CLOSE',
  FUNDED = 'FUNDED',
  WITHDRAWN = 'WITHDRAWN',
  DENIED = 'DENIED',
}

export enum TaskStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ConversationChannel {
  ASSISTANT = 'ASSISTANT',
  CHAT = 'CHAT',
  EMAIL = 'EMAIL',
  CALL = 'CALL',
}

export enum WorkflowTriggerType {
  STATUS_CHANGE = 'STATUS_CHANGE',
  TIME_BASED = 'TIME_BASED',
  INTERACTION_LOG = 'INTERACTION_LOG',
}

export enum OutboundEventStatus {
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
}
